services:
  mysql:
    image: mysql:8.4.2
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
    networks:
      - redis-spring-jpa
  app:
    depends_on:
      - redis
    build: .
    image: foogaro/redis-spring-jpa:latest
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    stdin_open: true
    tty: true
    networks:
      - redis-spring-jpa
  redis:
    depends_on:
      - mysql
    image: redis/redis-stack-server:7.4.0-v1
    container_name: redis
    cap_add:
      - SYS_RESOURCE
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - redis-spring-jpa
networks:
  redis-spring-jpa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
volumes:
  db: